# Generated by Django 5.0.4 on 2024-04-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.task'),
        ),
    ]
